export const arr = [
    "Desayunos",
    "Comidas",
    "Cenas",
    "Aperitivos",
    "Antojitos",
    "Bebidas",
    "Rápida",
    "Postres",
    "Desayunos",
    "Comidas",
    "Cenas",
    "Aperitivos",
    "Antojitos",
    "Bebidas",
    "Rápida",
    "Postres",
  ];